### ISSUE TITLE
EPSMA

### ISSUE THREAD

**Issue by victorstewart** [ashvardanian/SubstringSearchBenchmark#3]
have you avoided implementing EPSMA because AVX2 in your tests is memory bound anyway so that's the point?

[https://vecpar2018.ncc.unesp.br/wp-content/uploads/2018/09/VECPAR_2018_paper_22.pdf](https://vecpar2018.ncc.unesp.br/wp-content/uploads/2018/09/VECPAR_2018_paper_22.pdf)

**Comment by ashvardanian** [comment]
I am not familiar with that specific algorithm, but it seems like it's EPSMc sub-procedure computes fingerprints/hashes, if the query is long enough. It is a relatively complicated general-purpose algorithm (both computation and implementation wise), while this repo is a simple comparison, that should fit into a 1 hour talk. The implemented heuristic (checking only the 4-byte prefix with AVX2 and doing the rest without SIMD) was good enough for that job.
