### ISSUE TITLE
Benchmark Discrepancies Across Implementations

### ISSUE THREAD

**Issue by victorstewart** [ashvardanian/SubstringSearchBenchmark#4]
just wondering if you have any comment as to why your benchmarks show such a wide gap between std::strstr and avx2 and avx512 when these ones from sse4-strstr show basically no gain unless you're using AVX512F or AVX512BW, and then only twice the throughput?

is your implementation just that much better?

I'm away from my machines right now but will run my own benchmarks next week!

[https://github.com/WojciechMula/sse4-strstr/blob/master/results/cascadelake-Gold-5217-gcc-7.4.0-avx512bw.txt](https://github.com/WojciechMula/sse4-strstr/blob/master/results/cascadelake-Gold-5217-gcc-7.4.0-avx512bw.txt)

**Comment by ashvardanian** [comment]
@victorstewart Hi! Did you try running the benchmarks?
